spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kyapi?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456